export const topics = [
  { id: 1, text: "Wild Animals", emoji: "🦁" },
  { id: 2, text: "Pets", emoji: "🐕" },
  { id: 3, text: "Ocean Creatures", emoji: "🐠" },
  { id: 4, text: "Birds", emoji: "🦅" },
  { id: 5, text: "Insects", emoji: "🦋" },
  { id: 6, text: "Dinosaurs", emoji: "🦕" },
  { id: 7, text: "Dragons", emoji: "🐉" },
  { id: 8, text: "Monsters", emoji: "👾" },
  { id: 9, text: "Robots", emoji: "🤖" },
  { id: 10, text: "Aliens", emoji: "👽" },
  { id: 11, text: "Superheroes", emoji: "🦸" },
  { id: 12, text: "Princesses & Knights", emoji: "👑" },
  { id: 13, text: "Pirates", emoji: "🏴‍☠️" },
  { id: 14, text: "Ninjas", emoji: "🥷" },
  { id: 15, text: "Wizards", emoji: "🧙" },
  { id: 16, text: "Fairies", emoji: "🧚" },
  { id: 17, text: "Mermaids", emoji: "🧜" },
  { id: 18, text: "Space & Planets", emoji: "🪐" },
  { id: 19, text: "Weather", emoji: "⛈️" },
  { id: 20, text: "Seasons", emoji: "🍂" },
  { id: 21, text: "Food & Snacks", emoji: "🍕" },
  { id: 22, text: "Desserts", emoji: "🍰" },
  { id: 23, text: "Vehicles", emoji: "🚗" },
  { id: 24, text: "Buildings", emoji: "🏢" },
  { id: 25, text: "Trees & Plants", emoji: "🌳" },
  { id: 26, text: "Flowers", emoji: "🌻" },
  { id: 27, text: "Sports", emoji: "⚽" },
  { id: 28, text: "Musical Instruments", emoji: "🎸" },
  { id: 29, text: "Toys", emoji: "🧸" },
  { id: 30, text: "School Supplies", emoji: "✏️" },
  { id: 31, text: "Emotions/Feelings", emoji: "😊" },
  { id: 32, text: "Underwater World", emoji: "🐙" },
  { id: 33, text: "Circus", emoji: "🎪" },
  { id: 34, text: "Farm Life", emoji: "🚜" },
  { id: 35, text: "Jungle Adventure", emoji: "🌴" },
  { id: 36, text: "Arctic Animals", emoji: "🐧" },
  { id: 37, text: "Desert Life", emoji: "🌵" },
  { id: 38, text: "Mythical Creatures", emoji: "🦄" },
  { id: 39, text: "Household Items", emoji: "🏠" },
  { id: 40, text: "Playground Equipment", emoji: "🎠" }
];

export const constraints = [
  { id: 1, text: "One continuous line", emoji: "✏️" },
  { id: 2, text: "Use only circles", emoji: "⭕" },
  { id: 3, text: "Use only squares", emoji: "⬜" },
  { id: 4, text: "Non-dominant hand", emoji: "🤚" },
  { id: 5, text: "Draw upside down", emoji: "🙃" },
  { id: 6, text: "Eyes closed", emoji: "😑" },
  { id: 7, text: "Use only dots", emoji: "•" },
  { id: 8, text: "Draw in 30 seconds", emoji: "⏱️" },
  { id: 9, text: "Tiny (thumb-sized)", emoji: "🤏" },
  { id: 10, text: "HUGE (fill the page)", emoji: "📄" },
  { id: 11, text: "Use only 3 colors", emoji: "🎨" },
  { id: 12, text: "Make it rainbow", emoji: "🌈" },
  { id: 13, text: "Only straight lines", emoji: "📏" },
  { id: 14, text: "Only curved lines", emoji: "〰️" },
  { id: 15, text: "Add patterns everywhere", emoji: "🔲" },
  { id: 16, text: "Make it symmetrical", emoji: "🪞" },
  { id: 17, text: "Robot version", emoji: "🤖" },
  { id: 18, text: "Draw it melting", emoji: "💧" },
  { id: 19, text: "Draw it flying", emoji: "🕊️" },
  { id: 20, text: "Add silly accessories", emoji: "🎩" },
  { id: 21, text: "Draw it dancing", emoji: "💃" },
  { id: 22, text: "Make it look angry", emoji: "😠" },
  { id: 23, text: "Make it look happy", emoji: "😄" },
  { id: 24, text: "Draw it wearing a hat", emoji: "🧢" },
  { id: 25, text: "Give it superpowers", emoji: "⚡" },
  { id: 26, text: "Baby version", emoji: "👶" },
  { id: 27, text: "Make it sparkly", emoji: "✨" },
  { id: 28, text: "Draw it in a storm", emoji: "🌩️" },
  { id: 29, text: "Draw it sleeping", emoji: "😴" },
  { id: 30, text: "Shapes only", emoji: "🔷" }
];

export const wheelColors = [
  "#FF6B6B", "#4ECDC4", "#45B7D1", "#96CEB4", "#FECA57",
  "#FF9FF3", "#54A0FF", "#48DBFB", "#1ABC9C", "#F39C12",
  "#E74C3C", "#9B59B6", "#3498DB", "#2ECC71", "#F1C40F",
  "#E67E22", "#16A085", "#27AE60", "#2980B9", "#8E44AD"
];